# Generated by Django 4.2 on 2025-01-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_layer', '0002_remove_input_timestamp_input_created_at_and_more'),
        ('output_layer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='input_layer.input'),
        ),
    ]
