# Generated by Django 4.2 on 2025-01-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('output_layer', '0002_alter_output_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Output',
        ),
    ]
